### ISSUE TITLE
Chapter 1 source code is missing

### ISSUE THREAD

**Issue by hkarakose** [learning-ionic/Chapter-1#1]
Hello
Chapter 1 source code does not exist in repository. Can you upload the chapter 1 code?

**Comment by arvindr21** [comment]
@hkarakose this chapter doesn't have any code.

**Comment by hkarakose** [comment]
There is source code in chapter 1 text. Here is a screenshot from chapter 1.

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/406291/27204392-a2091ce2-5233-11e7-84fc-72c37a54957d.png">

**Comment by arvindr21** [comment]
This is learning ionic second edition. Here is the link :
https://github.com/PacktPublishing/Learning-Ionic-Second-Edition

On Jun 16, 2017 04:02, "Halil Karakose" <notifications@github.com> wrote:

There is source code in chapter 1 text. Here is a screenshot from chapter 1.

[image: image]
<https://user-images.githubusercontent.com/406291/27204392-a2091ce2-5233-11e7-84fc-72c37a54957d.png>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/learning-ionic/Chapter-1/issues/1#issuecomment-308883689>,
or mute the thread

**Comment by hkarakose** [comment]
Thanks.
